GO
USE [BHSDB];
GO


create PROCEDURE dbo.stp_RPT_CLT_SortCorrelation
		  @SDO datetime , 
		  @AIRLINE varchar(max)
AS
BEGIN
	PRINT 'BAGTAG STORED PROCEDURE BEGIN';
	DECLARE @DATERANGE INT=1;

	SET @SDO=CONVERT(DATETIME,CONVERT(VARCHAR,@SDO,103),103);

	--Create temp table for final result
	CREATE TABLE #SC_SortCorrelation_TEMP 
	(
		SDO datetime,
		AIRLINE varchar(3),
		FLIGHT_NUMBER varchar(5),
		DESTINATION varchar(3),
		CLOSEOUT_TIME datetime,
		DEPARTURE_TIME datetime,
		SORTED_MU varchar(100),
		DEFAULT_MU varchar(10),
		FLIGHT_DAYS varchar(15),
		PRIMARY_MU varchar(100),
		FIRST_MU varchar(10),
		BUSINESS_MU varchar(10),
		HOT_MU varchar(10),
		LATE_MU varchar(10),
		STANDBY_MU varchar(10),
	);

	--1. Query flight info into final table
	INSERT INTO #SC_SortCorrelation_TEMP
	SELECT DISTINCT fpa.SDO, fpa.AIRLINE, fpa.FLIGHT_NUMBER, fpa.FLIGHT_DESTINATION, 
		MAX(CASE FPA.ALLOC_CLOSE_RELATED
			WHEN 'ETD' 
				--THEN CONVERT(DATETIME,CONVERT(VARCHAR,FPA.EDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(dbo.SAC_OFFSETOPERATOR(FPA.ETO,FPA.ALLOC_CLOSE_OFFSET)),103)
				THEN DBO.RPT_TIME_CAL(FPA.EDO,FPA.ETO,FPA.ALLOC_CLOSE_OFFSET)
			ELSE 
				--CONVERT(DATETIME,CONVERT(VARCHAR,FPA.SDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(dbo.SAC_OFFSETOPERATOR(FPA.STO,FPA.ALLOC_CLOSE_OFFSET)),103)
				DBO.RPT_TIME_CAL(FPA.SDO,FPA.STO,FPA.ALLOC_CLOSE_OFFSET)
		END) AS CLOSEOUT_TIME,
		CASE 
			WHEN FPA.EDO IS NULL 
				THEN CONVERT(DATETIME,CONVERT(VARCHAR,FPA.SDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(FPA.STO),103)
			ELSE 
				CONVERT(DATETIME,CONVERT(VARCHAR,FPA.EDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(FPA.ETO),103)
		END AS DEPARTURE_TIME,
		'' AS SORTED_MU,
		'' AS DEFAULT_MU,
		'' AS FLIGHT_WEEKDAYS,
		'' AS PRIMARY_MU, '' AS FIRST_MU, '' AS BUSINESS_MU, '' AS HOT_MU, '' AS LATE_MU, '' AS STANDBY_MU
	FROM FLIGHT_PLAN_ALLOC fpa WITH(NOLOCK)
	WHERE fpa.SDO=@SDO AND fpa.AIRLINE IN (SELECT * FROM DBO.RPT_GETPARAMETERS(@AIRLINE)) 
	GROUP BY  fpa.SDO, fpa.AIRLINE, fpa.FLIGHT_NUMBER, fpa.FLIGHT_DESTINATION,
		CASE 
			WHEN FPA.EDO IS NULL THEN CONVERT(DATETIME,CONVERT(VARCHAR,FPA.SDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(FPA.STO),103)
			ELSE CONVERT(DATETIME,CONVERT(VARCHAR,FPA.EDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(FPA.ETO),103)
		END 

	
	--2. Update first, business, hot, late and standby MU into final table
	UPDATE SST
	SET SST.DEFAULT_MU=AIR.DESTINATION
	FROM AIRLINES AIR,#SC_SortCorrelation_TEMP SST
	WHERE AIR.CODE_IATA=SST.AIRLINE;--DEFAULT_MU

	UPDATE #SC_SortCorrelation_TEMP
	SET #SC_SortCorrelation_TEMP.FIRST_MU=FAL.RESOURCE
	FROM FUNCTION_ALLOC_LIST FAL
	WHERE FAL.FUNCTION_TYPE='FCPB';--FIRST
	
	UPDATE #SC_SortCorrelation_TEMP
	SET #SC_SortCorrelation_TEMP.BUSINESS_MU=FAL.RESOURCE
	FROM FUNCTION_ALLOC_LIST FAL
	WHERE FAL.FUNCTION_TYPE='BCPB';--BUSINESS
	
	UPDATE #SC_SortCorrelation_TEMP
	SET #SC_SortCorrelation_TEMP.HOT_MU=FAL.RESOURCE
	FROM FUNCTION_ALLOC_LIST FAL
	WHERE FAL.FUNCTION_TYPE='RUSH';--RUSH OR HOT
	
	UPDATE #SC_SortCorrelation_TEMP
	SET #SC_SortCorrelation_TEMP.LATE_MU=FAL.RESOURCE
	FROM FUNCTION_ALLOC_LIST FAL
	WHERE FAL.FUNCTION_TYPE='LATE';--LATE
	
	UPDATE #SC_SortCorrelation_TEMP
	SET #SC_SortCorrelation_TEMP.STANDBY_MU=FAL.RESOURCE
	FROM FUNCTION_ALLOC_LIST FAL
	WHERE FAL.FUNCTION_TYPE='SBPB';--STANDBY
	
	
	--CREATE TYPE ALLOCINFO_TABLETYPE AS TABLE 
	--( 
	--	AIRLINE varchar(3),
	--	FLIGHT_NUMBER varchar(5),
	--	SDO datetime,
	--	ALLOCINFO VARCHAR(10)
	--);

	--CREATE TYPE ALLOCCOMINFO_TABLETYPE AS TABLE
	--( 
	--	AIRLINE varchar(3),
	--	FLIGHT_NUMBER varchar(5),
	--	SDO datetime,
	--	COMBINEINFO VARCHAR(200)
	--);

	--3. Update primary MU and sorted MU into final table
	DECLARE @SC_ALLOCINFO_TABLE AS ALLOCINFO_TABLETYPE; --For the parameter of stp_RPT_AllocInfoCombine
	DECLARE @SC_COMBINEINFO_TABLE AS ALLOCCOMINFO_TABLETYPE;--For the result of stp_RPT_AllocInfoCombine
	
	INSERT INTO @SC_ALLOCINFO_TABLE
	SELECT DISTINCT SC.AIRLINE,SC.FLIGHT_NUMBER,SC.SDO,FPA.RESOURCE
	FROM #SC_SortCorrelation_TEMP SC, FLIGHT_PLAN_ALLOC fpa WITH(NOLOCK)
	WHERE SC.AIRLINE=FPA.AIRLINE AND SC.FLIGHT_NUMBER=FPA.FLIGHT_NUMBER AND SC.SDO=FPA.SDO

	INSERT INTO @SC_COMBINEINFO_TABLE
	EXEC DBO.stp_RPT_AllocInfoCombine @SC_ALLOCINFO_TABLE

	UPDATE SC
	SET SC.SORTED_MU=COMB.COMBINEINFO, SC.PRIMARY_MU=COMB.COMBINEINFO
	FROM #SC_SortCorrelation_TEMP SC, @SC_COMBINEINFO_TABLE COMB
	WHERE SC.AIRLINE=COMB.AIRLINE AND SC.FLIGHT_NUMBER=COMB.FLIGHT_NUMBER AND SC.SDO=COMB.SDO;

	--4. Update weekday (FLIGHT_WEEKDAYS) into final table
	DELETE @SC_ALLOCINFO_TABLE;
	DELETE @SC_COMBINEINFO_TABLE;

	INSERT INTO @SC_ALLOCINFO_TABLE
	SELECT DISTINCT SC.AIRLINE,SC.FLIGHT_NUMBER,SC.SDO AS SDO,fpa.WEEKDAY
	FROM #SC_SortCorrelation_TEMP SC, FLIGHT_PLAN_ALLOC fpa WITH(NOLOCK)
	WHERE SC.AIRLINE=FPA.AIRLINE AND SC.FLIGHT_NUMBER=FPA.FLIGHT_NUMBER
		--AND FPA.SDO BETWEEN DATEADD(DAY,-@DATERANGE,@SDO) AND DATEADD(DAY,@DATERANGE,@SDO);
		AND FPA.SDO BETWEEN @SDO AND DATEADD(DAY,@DATERANGE,@SDO);

	--SELECT * FROM @SC_ALLOCINFO_TABLE;

	INSERT INTO @SC_COMBINEINFO_TABLE
	EXEC DBO.stp_RPT_AllocInfoCombine @SC_ALLOCINFO_TABLE

	--SELECT * FROM @SC_COMBINEINFO_TABLE;

	UPDATE SC
	SET SC.FLIGHT_DAYS=COMB.COMBINEINFO
	FROM #SC_SortCorrelation_TEMP SC, @SC_COMBINEINFO_TABLE COMB
	WHERE SC.AIRLINE=COMB.AIRLINE AND SC.FLIGHT_NUMBER=COMB.FLIGHT_NUMBER-- AND SC.SDO=COMB.SDO;

	SELECT DISTINCT * FROM #SC_SortCorrelation_TEMP SC;
END


--DECLARE @AIRLINE VARCHAR(MAX)='AA, AC, B6, BA, BR, DL, UA, US';
--DECLARE @SDO DATETIME='2014/1/7';
--EXEC stp_RPT04_SortCorrelation_GWYTEST @SDO,@AIRLINE;