GO
USE [BHSDB];
GO


ALTER PROCEDURE dbo.stp_RPT_CLT_EquipFaultSummary
		  @DTFrom datetime, 
		  @DTTo datetime,
		  @FaultType varchar(max)
AS
BEGIN

	SELECT	ALM_ALMAREA2,
			DATEDIFF(SECOND,ALM_STARTTIME,ALM_ENDTIME) AS ALM_DURATION
	INTO #EFS_ALARM_DETAIL_TEMP
	FROM	MDS_ALARMS WITH(NOLOCK)
	WHERE	ALM_UNCERTAIN = 0
			AND ALM_STARTTIME BETWEEN @DTFrom AND @DTTo 
			AND ALM_ALMAREA2 IN (SELECT * FROM dbo.RPT_GETPARAMETERS(@FaultType));

	SELECT	EAD.ALM_ALMAREA2,
			ISNULL(RF.FAULT_DESCRIPTION, EAD.ALM_ALMAREA2) AS EQUIP_FAULTTYPE, 
			COUNT(EAD.ALM_ALMAREA2) AS OCCURRENCES, 
			SUM(EAD.ALM_DURATION) AS FAULT_DURATION
	FROM #EFS_ALARM_DETAIL_TEMP EAD
	LEFT JOIN REPORT_FAULT RF ON EAD.ALM_ALMAREA2=RF.FAULT_NAME
	GROUP BY EAD.ALM_ALMAREA2,RF.FAULT_DESCRIPTION;

	DROP TABLE #EFS_ALARM_DETAIL_TEMP;

END

--DECLARE @DTFrom datetime='2009-12-01';
--DECLARE @DTTo datetime='2009-12-31';
--DECLARE @FaultType varchar(max)='AA_ENUS,AA_BJAM,AA_ESTP,AA_ENUS,AA_ISOF,AA_CNFT';
--EXEC stp_RPT08_EquipFaultSummary @DTFrom,@DTTo,@FaultType;