GO
USE [BHSDB];
GO



ALTER PROCEDURE dbo.stp_RPT10_LOADBALANCING_EDS
		  @DTFROM DATETIME,
		  @DTTO DATETIME
AS
BEGIN
--PROBLEM1: only machine(lvl1) result or levle1&2 result

	PRINT 'BAGTAG STORED PROCEDURE BEGIN';
	DECLARE @DATERANGE INT=1;

	--1. Insert item_screened data into a temp table
	SELECT LOCATION,GID,SCREEN_LEVEL,TIME_STAMP,RESULT_TYPE
	INTO #EDS_ITEM_SCREENED_TEMP
	FROM ITEM_SCREENED WITH(NOLOCK)
	WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo;

	--2. create a temp table for machine result
	CREATE TABLE #EDS_STATUS_TEMP
	(
		SUBSYSTEM_TYPE VARCHAR(30),
		SUBSYSTEM VARCHAR(20),
		LOCATION VARCHAR(20),
		BAGS INT,
		BAGS_CLEARED INT,
		BAGS_ALARMED INT,
		CLEARED_RATE FLOAT
	)

	--Insert EDS machines screened result into #EDS_STATUS_TEMP
	--3. total number of bags
	INSERT INTO #EDS_STATUS_TEMP
	SELECT 'EDS MACHINES' AS SUBSYSTEM_TYPE,LOC.SUBSYSTEM, LOC.LOCATION, COUNT(ICR.GID) AS BAGS, 0 AS BAGS_CLEARED, 0 AS BAGS_ALARMED, 0 AS CLEARED_RATE
	FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
	WHERE ICR.LOCATION=LOC.LOCATION_ID
		--AND ICR.SCREEN_LEVEL='3'
	GROUP BY LOC.SUBSYSTEM, LOC.LOCATION;


	--4. cleared bag
	UPDATE EST
	SET EST.BAGS_CLEARED=CLR.CLEARED_CNT
	FROM
	(
		SELECT LOC.LOCATION,COUNT(ICR.GID) AS CLEARED_CNT
		FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
		WHERE LOC.LOCATION_ID=ICR.LOCATION
			--AND ICR.SCREEN_LEVEL='3'
			AND (ICR.RESULT_TYPE='12' OR ICR.RESULT_TYPE='22')--CLEARED
		GROUP BY LOC.LOCATION
	) AS CLR, #EDS_STATUS_TEMP EST
	WHERE EST.LOCATION=CLR.LOCATION;

	--5. alarmed bag
	UPDATE EST
	SET EST.BAGS_ALARMED=ALM.ALARMED_CNT
	FROM
	(
		SELECT LOC.LOCATION,COUNT(ICR.GID) AS ALARMED_CNT
		FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
		WHERE LOC.LOCATION_ID=ICR.LOCATION
			--AND ICR.SCREEN_LEVEL='3'
			AND (ICR.RESULT_TYPE<>'12' AND ICR.RESULT_TYPE<>'22')--ALARMED
		GROUP BY LOC.LOCATION
	) AS ALM, #EDS_STATUS_TEMP EST
	WHERE EST.LOCATION=ALM.LOCATION;


	--6. cleared rate
	UPDATE EST
	SET EST.CLEARED_RATE=CAST(BAGS_CLEARED AS FLOAT)/CAST(BAGS AS FLOAT)*100
	FROM #EDS_STATUS_TEMP EST;

	--7. count the bags by different matrix (east and west)
	--And finally select all the result.
	SELECT 'EDS MATRIX' AS SUBSYSTEM_TYPE,
		CASE 
			WHEN SUBSYSTEM IN ('ED1','ED2','ED3','ED4') THEN 'WEST MATRIX'
			WHEN SUBSYSTEM IN ('ED7','ED8','ED9','ED10','ED11') THEN 'EAST MATRIX'
			ELSE 'UNKNOW MATRIX'
		END AS SUBSYSTEM_M,
		SUM(BAGS) AS BAGS,
		SUM(BAGS_CLEARED) AS BAGS_CLEARED,
		SUM(BAGS_ALARMED) AS BAGS_ALARMED,
		CAST(SUM(BAGS_CLEARED) AS FLOAT)/CAST(SUM(BAGS) AS FLOAT)*100 AS CLEARED_RATE
	FROM #EDS_STATUS_TEMP EST
	GROUP BY 
		CASE 
			WHEN SUBSYSTEM IN ('ED1','ED2','ED3','ED4') THEN 'WEST MATRIX'
			WHEN SUBSYSTEM IN ('ED7','ED8','ED9','ED10','ED11') THEN 'EAST MATRIX'
			ELSE 'UNKNOW MATRIX'
		END

	UNION ALL
	SELECT SUBSYSTEM_TYPE, SUBSYSTEM, BAGS, BAGS_CLEARED,BAGS_ALARMED, CLEARED_RATE
	FROM #EDS_STATUS_TEMP

	

END

DECLARE @DTFrom [datetime]='2013-12-30';
DECLARE @DTTo [datetime]='2014-01-01';
EXEC stp_RPT10_LOADBALANCING_EDS @DTFrom,@DTTo;

--SELECT * FROM ITEM_SCREEN_RESULT_TYPES;

--DECLARE @DTFrom [datetime]='2013-12-10';
--DECLARE @DTTo [datetime]='2013-12-27';
--SELECT * FROM ITEM_SCREENED ICR 
--WHERE ICR.TIME_STAMP BETWEEN @DTFrom AND @DTTo
--	AND (ICR.RESULT_TYPE<>'12' AND ICR.RESULT_TYPE<>'22');