--13.1 EDS MACHINE STATUS REPORT
GO
USE [BHSDB_CLT];
GO

--1. EDS MACHINE	

--2. PLC BANK
SELECT	MELM.EQUIP_ID, 
		MESV.STATUS_NAME AS 'ONOFF_STATUS',
		( SELECT MESV2.STATUS_NAME
		  FROM MIS_EQUIP_LIVE_MONITOR MELM2, MIS_EQUIP_STATUS_VALUEMAP MESV2
		  WHERE MELM2.STATUS_CLASS=MESV2.STATUS_CLASS
				AND MELM2.CURRENT_STATUS=MESV2.STATUS_VALUE
				AND MELM2.EQUIP_ID=MELM.EQUIP_ID
				AND MELM.STATUS_CLASS='PRI_SEC'
		 ) AS 'WORKING_STATUS'
FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
	AND MELM.EQUIP_ID LIKE 'PLC%'
	AND MELM.STATUS_CLASS='ON_OFFLINE'
	AND EXISTS(SELECT EQUIP_SUBSYSTEM FROM MIS_DEVICE_PLC_MAP WHERE PLC_ID=MELM.EQUIP_ID AND EQUIP_SUBSYSTEM LIKE 'ED%');

SELECT	STA.LOCATION, 
		STAL.DESCRIPTION  AS 'ONOFF_STATUS',
		CASE STAL.DESCRIPTION
			WHEN 'OFFLINE' THEN 'Standby' 
			WHEN 'ONILNE' THEN 'Running'
		END	AS 'WORKING_STATUS'
FROM	MDS_STATUS STA, MDS_STATUS_LK STAL, MIS_DEVICE_PLC_MAP DPM
WHERE	STA.TYPE='NETWORK' 
	AND STA.TYPE=STAL.TYPE 
	AND STA.TYPE_STATUS=STAL.TYPE_STATUS 
	AND LTRIM(RTRIM(STA.STATUS))=LTRIM(RTRIM(STAL.FIX))
	AND STAL.DESC_TYPE='FIX'
	--AND STA.LOCATION LIKE 'PLC%'
	AND DPM.EQUIP_SUBSYSTEM LIKE 'ED%' 
	AND DPM.PLC_OTHERNAME=STA.LOCATION
ORDER BY STA.LOCATION

--3. COMMUNICATION INTERFACE MODULE
