--13.1 EDS MACHINE STATUS REPORT
GO
USE [BHSDB];
GO

--1. EDS MACHINE	

--2. PLC BANK
SELECT	MELM.EQUIP_ID, 
		MESV.STATUS_NAME AS 'ONOFF_STATUS',
		( SELECT MESV2.STATUS_NAME
		  FROM MIS_EQUIP_LIVE_MONITOR MELM2, MIS_EQUIP_STATUS_VALUEMAP MESV2
		  WHERE MELM2.STATUS_CLASS=MESV2.STATUS_CLASS
				AND MELM2.CURRENT_STATUS=MESV2.STATUS_VALUE
				AND MELM2.EQUIP_ID=MELM.EQUIP_ID
				AND MELM.STATUS_CLASS='PRI_SEC'
		 ) AS 'WORKING_STATUS'
FROM	MIS_EQUIP_LIVE_MONITOR MELM, MIS_EQUIP_STATUS_VALUEMAP MESV
WHERE	MELM.STATUS_CLASS=MESV.STATUS_CLASS
	AND MELM.CURRENT_STATUS=MESV.STATUS_VALUE
	AND MELM.EQUIP_ID LIKE 'PLC%'
	AND MELM.STATUS_CLASS='ON_OFFLINE'
	AND EXISTS(SELECT EQUIP_SUBSYSTEM FROM MIS_DEVICE_PLC_MAP WHERE PLC_ID=MELM.EQUIP_ID AND EQUIP_SUBSYSTEM LIKE 'ED%');

--3. COMMUNICATION INTERFACE MODULE
