GO
USE [BHSDB_CLT_Demo];
GO


alter PROCEDURE dbo.stp_RPT_CLT_SortAreaAssignment
		  @DTFrom datetime , 
		  @DTTo datetime
AS
BEGIN
	PRINT 'SortAreaAssignment STORED PROCEDURE BEGIN';

	--SELECT frc.TIME_STAMP,frc.AIRLINE,frc.FLIGHT_NUMBER,frc.FLIGHT_NUMBER_SUFFIX,frc.SDO,frc.STO,frc.EDO,frc.ETO,frc.CURRENT_RESOURCE,frc.NEW_RESOURCE,frc.CREATED_BY
	--FROM FLIGHT_RESOURCE_CHANGE frc
	--WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo

	SELECT	AR.RESOURCE as Physical_MakeUp,AR.RESOURCE as AssignedTo
	FROM	ALLOC_RESOURCES AR
END