	
	--1. Insert item_screened data into a temp table
	SELECT LOCATION,GID,SCREEN_LEVEL,TIME_STAMP,RESULT_TYPE
	INTO #EDS_ITEM_SCREENED_TEMP
	FROM ITEM_SCREENED WITH(NOLOCK)
	WHERE TIME_STAMP BETWEEN @DTFrom AND @DTTo;

	--2. create a temp table for machine result
	CREATE TABLE #EDS_STATUS_TEMP
	(
		SUBSYSTEM_TYPE VARCHAR(30),
		SUBSYSTEM VARCHAR(20),
		LOCATION VARCHAR(20),
		BAGS INT,
		BAGS_CLEARED INT,
		BAGS_ALARMED INT,
		CLEARED_RATE FLOAT
	)

	--6 select eds machine(level1) result detail into a temp table
	SELECT LOC.SUBSYSTEM,ICR.GID, ICR.TIME_STAMP, 
		CASE 
			WHEN ICR.RESULT_TYPE LIKE '2%' THEN 'CLEARED'
			ELSE 'ALARMED'
		END AS RESULT
	INTO #EDS_RESULT_TEMP
	FROM #EDS_ITEM_SCREENED_TEMP ICR, LOCATIONS LOC
	WHERE ICR.SCREEN_LEVEL='1'
		AND ICR.LOCATION=LOC.LOCATION_ID

	--7 update eds result for #EDS_RESULT_TEMP by level 2 screened result
	UPDATE ERT
	SET ERT.RESULT=
		CASE
			WHEN ICR.RESULT_TYPE='12' OR ICR.RESULT_TYPE='22' THEN 'CLEARED'
			WHEN ICR.RESULT_TYPE='11' OR ICR.RESULT_TYPE='21' THEN 'ALARMED'
			ELSE 'ALARMED'
		END
	FROM #EDS_RESULT_TEMP ERT, #EDS_ITEM_SCREENED_TEMP ICR
	WHERE ERT.GID=ICR.GID
		AND ICR.SCREEN_LEVEL='2'

	--8 Insert subsystem final screened result into #EDS_STATUS_TEMP
	INSERT INTO #EDS_STATUS_TEMP
	SELECT 'EDS MATRIX' AS SUBSYSTEM_TYPE,ERT.SUBSYSTEM AS REGION_ID, COUNT(DISTINCT ERT.GID) AS BAGS, NULL AS BAGS_CLEARED, NULL AS BAGS_ALARMED, NULL AS CLEARED_RATE
	FROM #EDS_RESULT_TEMP ERT
	GROUP BY ERT.SUBSYSTEM

	UPDATE EST
	SET EST.BAGS_CLEARED=EDSMATRIX_CLR.CLEARED_CNT
	FROM 
	(	SELECT ERT.SUBSYSTEM,COUNT(DISTINCT ERT.GID) AS CLEARED_CNT
		FROM #EDS_RESULT_TEMP ERT
		WHERE ERT.RESULT='CLEARED'
	)AS EDSMATRIX_CLR, #EDS_STATUS_TEMP EST
	WHERE EST.REGION_ID=EDSMATRIX_CLR.SUBSYSTEM

	UPDATE EST
	SET EST.BAGS_ALARMED=EDSMATRIX_ALM.ALARMED_CNT
	FROM 
	(	SELECT ERT.SUBSYSTEM,COUNT(DISTINCT ERT.GID) AS ALARMED_CNT
		FROM #EDS_RESULT_TEMP ERT
		WHERE ERT.RESULT='ALARMED'
	)AS EDSMATRIX_ALM, #EDS_STATUS_TEMP EST
	WHERE EST.REGION_ID=EDSMATRIX_ALM.SUBSYSTEM
