GO
USE [BHSDB_CLT_Demo];
GO

--Simple Bag Volume Statistics

ALTER PROCEDURE dbo.stp_RPT_CLT_Simple_STAT_BagVolume
		  @DTFrom DATETIME,
		  @DTTo DATETIME
AS
BEGIN
	DECLARE	@QTY_NORMAL INT=0;
	DECLARE	@QTY_OOG INT=0;
	DECLARE	@QTY_OS INT=0;

	--NORMAL
	SELECT	@QTY_NORMAL = COUNT(IM.GID)
	FROM	ITEM_MEASURED IM
	WHERE	IM.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
		AND IM.TYPE='2'

	SELECT	@QTY_OOG = COUNT(IM.GID)
	FROM	ITEM_MEASURED IM
	WHERE	IM.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
		AND IM.TYPE='1'

	SELECT	@QTY_OS = SUM(DIFFERENT)
	FROM	MDS_COUNT MBC, MDS_COUNTERS MBCR
	WHERE	MBC.COUNTER_ID=MBCR.COUNTER_ID
		AND MBC.TIME_STAMP BETWEEN @DTFrom AND @DTTo 
		AND MBCR.LOCATION = 'OS1-3'

	IF @QTY_NORMAL IS NULL SET @QTY_NORMAL=0;
	IF @QTY_OOG IS NULL SET @QTY_OOG=0;
	IF @QTY_OS IS NULL SET @QTY_OS=0;

	SELECT @QTY_NORMAL AS QTY_NORMAL, @QTY_OOG AS QTY_OOG, @QTY_OS AS QTY_OS, @QTY_NORMAL+@QTY_OOG+@QTY_OS AS TOTAL
END