BEGIN TRAN

DROP PROCEDURE dbo.stp_RPT_BAGTAG_GWYTEST

SELECT * INTO BAG_SORTING_HIS FROM BAG_SORTING bs ;

SELECT * FROM BAG_SORTING_HIS;
SELECT * FROM BAG_SORTING bs;
SELECT * FROM BAG_INFO bi;
SELECT * INTO BAG_INFO_HIS FROM BAG_INFO bi WHERE bi.TIME_STAMP<'2013-11-15';


SELECT (BSH.GIVEN_NAME+' '+BSH.SURNAME) AS PAX_NAME FROM BAG_SORTING_HIS BSH;

SELECT * FROM ITEM_SCANNED;

SELECT TOP 5 * FROM FLIGHT_PLAN_ALLOC;

SELECT  * FROM ITEM_PROCEEDED;
SELECT * FROM LOCATIONS WHERE LOCATION LIKE 'MU%';

SELECT LICENSE_PLATE,GIVEN_NAME,SURNAME,OTHERS_NAME,FLIGHT_NUMBER,AIRLINE,SOURCE
		FROM BAG_SORTING
WITH(NOLOCK)

--2013-11-14 17:38:38.140	2113000103
--2013-11-15 09:14:54.743	2113000130
--2013-11-15 14:29:00.880	2113000203 --right

select * from ITEM_SCANNED where LICENSE_PLATE1='0612100001' ;

declare @holder varchar(10)='';
select distinct isc.LICENSE_PLATE1,isc.LICENSE_PLATE2,isc.LOCATION,@holder as GID into #test_isc
from ITEM_SCANNED isc
where isc.LICENSE_PLATE1='0612100001';

drop table #test_isc;

update new2
set new2.gid=new.gid
from (
select top 1 isc.gid,isc.LICENSE_PLATE1
from ITEM_SCANNED isc, #test_isc tisc
where tisc.license_plate1=isc.LICENSE_PLATE1
order by isc.time_stamp desc
) as new,#test_isc new2
WHERE new.LICENSE_PLATE1=new2.LICENSE_PLATE1;

select * from #test_isc;

SELECT * FROM BAG_SORTING;

SELECT * FROM ITEM_SORTATION_EVENT;
SELECT * FROM ITEM_SORTATION_EVENT_TYPES;
SELECT * FROM ITEM_PROCEED_TYPES;
SELECT * FROM ITEM_REDIRECT;
SELECT * FROM SORTATION_REASON;

SELECT * FROM FLIGHT_PLAN_ALLOC;
SELECT * FROM ITEM_ENCODING_REQUEST;
SELECT * FROM ITEM_ENCODING_REQUEST_TYPES;
SELECT * FROM ITEM_SCANNED WHERE STATUS_TYPE!='1';
SELECT * FROM ITEM_SCAN_STATUS_TYPES;

DECLARE @DATERANGE INT=1;
PRINT -@DATERANGE;

DROP TABLE TESTO;
CREATE TABLE TESTO
(
	TEST_DATE DATETIME,
	TEST_GID BIGINT,
	TEST_LP VARCHAR(10),
);
INSERT INTO TESTO
SELECT NULL AS TEST_DATE,NULL AS TEST_INT;

INSERT INTO TESTO
values('2013-12-01 12:00:00', 1,'0001');
INSERT INTO TESTO
values('2013-12-01 13:00:00', 11,'0001');
INSERT INTO TESTO
values('2013-12-01 14:00:00', 2,'0002');
INSERT INTO TESTO
values('2013-12-01 15:00:00', 22,'0002');
INSERT INTO TESTO
values('2013-12-02 15:00:00', 3,'0003');
INSERT INTO TESTO
values('2013-12-02 16:00:00', 3,'0003');

DECLARE @querydate datetime='2013-12-01'
SELECT * FROM TESTO t WHERE CONVERT(varchar,t.TEST_DATE,103)=CONVERT(varchar,@querydate,103);

SELECT CONVERT(datetime(8),t.TEST_DATE,103) FROM TESTO t;

DROP TABLE TEST2;
CREATE TABLE TEST2
(
	TEST_GID BIGINT,
	TEST_LP VARCHAR(10),
);

INSERT INTO TEST2
values(NULL, '0001');
INSERT INTO TEST2
values(NULL,'0002');
INSERT INTO TEST2
values(NULL,'0003');
INSERT INTO TEST2
values(NULL,'0004');

SELECT * INTO #TESTO_TEMP
FROM TESTO ORDER by TEST_DATE DESC;

UPDATE TEST2
SET TEST_GID=O.TEST_GID
FROM #TESTO_TEMP O
WHERE O.TEST_LP=TEST2.TEST_LP

SELECT * FROM TEST2;

SELECT TEST_LP,TEST_GID,
	CASE  
		WHEN (TEST_GID IS NULL or TEST_LP='0001') THEN 'NO'
		ELSE 'YES'
	END AS RES
FROM TEST2 t;

SELECT * FROM GID_USED;
SELECT * FROM ITEM_MEASURED im;
SELECT * FROM ITEM_MEASURED_TYPES imt;
SELECT * FROM ITEM_SCANNED;
SELECT * FROM ITEM_SCAN_STATUS_TYPES;
SELECT * FROM ITEM_TRACKING it;
SELECT * FROM ITEM_SCREENED;
SELECT * FROM ITEM_SCREEN_RESULT_TYPES isrt;
SELECT * FROM ITEM_PROCEEDED;
SELECT * FROM ITEM_PROCEED_TYPES;
SELECT * FROM ITEM_1500P ip;
SELECT * FROM ITEM_1500P_BAGSTATS ipb;
SELECT * FROM ITEM_REDIRECT ir;
SELECT * FROM SORTATION_REASON sr;
SELECT * FROM ITEM_ENCODING_REQUEST;
SELECT * FROM ITEM_ENCODING_REQUEST_TYPES;
SELECT * FROM ITEM_SORTATION_EVENT ise;
SELECT * FROM ITEM_SORTATION_EVENT_TYPES iset;
SELECT * FROM ITEM_LOST il;

SELECT DISTINCT SUBSYSTEM FROM LOCATIONS WHERE TRACKED=1;
SELECT * FROM LOCATIONS l WHERE l.LOCATION_ID='4';
SELECT * FROM LOCATIONS l WHERE L.SUBSYSTEM LIKE '%OOG%';
SELECT * FROM LOCATIONS l WHERE L.LOCATION LIKE '%EDS%';
SELECT * FROM ITEM_TRACKING

SELECT * FROM FLIGHT_PLAN_ALLOC fpa ORDER BY fpa.SDO DESC,fpa.AIRLINE, fpa.FLIGHT_NUMBER;
SELECT * FROM FLIGHT_PLANS fp;
SELECT * FROM FLIGHT_PLAN_SORTING fps;
SELECT * FROM FLIGHTS f;
SELECT * FROM FLIGHT_TYPE ft;
SELECT * FROM FLIGHT_RESOURCE_CHANGE frc;
SELECT * FROM BAG_SORTING bs;
SELECT bs.TRAVEL_CLASS FROM BAG_SORTING bs;
SELECT * FROM TRAVEL_CLASS tc;

SELECT * FROM ITEM_SORTATION_EVENT ise;
SELECT * FROM ITEM_SORTATION_EVENT_TYPES iset;	
SELECT * FROM CarrierCode cc;

SELECT * FROM FUNCTION_ALLOC_GANTT fag;
SELECT * FROM FUNCTION_ALLOC_LIST fal2;
SELECT * FROM FUNCTION_TYPES ft WHERE ft.DESCRIPTION LIKE '%default%';
SELECT * FROM FUNCTION_TYPE_GROUPS ftg;

SELECT * FROM FLIGHT_RESOURCE_CHANGE frc;

SELECT fal.*,ft.DESCRIPTION
FROM FUNCTION_ALLOC_LIST fal, FUNCTION_TYPES ft
WHERE fal.FUNCTION_TYPE=ft.TYPE;

DECLARE @AIRLINE VARCHAR(MAX)='AA,BB,CBX';
 SELECT * FROM DBO.RPT_GETPARAMETERS(@AIRLINE);

DECLARE @EDO DATETIME='2013-12-10 00:00:00';
declare @ETO varchar(4)='1200';
DECLARE @ALLOC_CLOSE_OFFSET VARCHAR(5)='-0040';

select dbo.SAC_OFFSETOPERATOR(@ETO,@ALLOC_CLOSE_OFFSET);

SELECT CONVERT(DATETIME,CONVERT(VARCHAR,@EDO,103) + ' ' + DBO.RPT_GETFORMATTEDSTO(dbo.SAC_OFFSETOPERATOR(@ETO,@ALLOC_CLOSE_OFFSET)),103);


DECLARE @TESTTABLE AS ALLOCINFO_TABLETYPE;
INSERT INTO @TESTTABLE
SELECT FPA.AIRLINE,FPA.FLIGHT_NUMBER,FPA.SDO,FPA.RESOURCE 
FROM FLIGHT_PLAN_ALLOC FPA
WHERE FPA.SDO='2013-12-09';

--SELECT * FROM @TESTTABLE;
DECLARE @finaltable AS ALLOCCOMINFO_TABLETYPE;
INSERT INTO @finaltable
EXEC DBO.stp_RPT_AllocInfoCombine @TESTTABLE;

SELECT F.COMBINEINFO FROM @finaltable F;
DELETE @finaltable;
SELECT * FROM @finaltable;

SELECT DISTINCT bag_type FROM FLIGHT_PLAN_ALLOC fpa;

SELECT COUNT(*) FROM BAG_SORTING bs;

SELECT * FROM LOCATIONS LOC WHERE LOC.SUBSYSTEM LIKE'%BDD' OR LOC.LOCATION LIKE'%BDD';
SELECT * FROM LOCATIONS LOC WHERE LOC.LOCATION_ID='1102';--SS1	SS1-2
SELECT * FROM LOCATIONS LOC WHERE LOC.LOCATION_ID='3302';
--SS2	SS2-2 1202 ATR
--ML03	ML3-2 3302 ATR

SELECT bhstbl.name, 
case bhstbl.xtype
when 'u' then 'table'
when 'p' then 'stored procedure'
else 'ohter' end as object_type
FROM BHSDB_Charlotte.sys.sysobjects as bhstbl
WHERE bhstbl.name like '%MEASURE%'
order by object_type; 

SELECT * FROM FALLBACK_MAPPING;
SELECT * FROM DESTINATION_CHUTE_MAPPING;
SELECT * FROM DESTINATION_PATH_MAPPING;
SELECT * FROM CHECKIN_COUNTER_LINE_MAPPING
SELECT * FROM CHECKIN_GROUP_MAPPING
SELECT * FROM CHECKIN_GROUP_RESOURCE_MAPPING

SELECT distinct MER.LOCATION,LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_ENCODING_REQUEST MER
LEFT JOIN LOCATIONS LOC
ON MER.LOCATION=LOC.LOCATION_ID;

SELECT * FROM LOCATIONS WHERE SUBSYSTEM LIKE '%ME%';
SELECT * FROM LOCATIONS --WHERE LOCATION_ID IN (
SELECT fal.*,ft.DESCRIPTION
FROM FUNCTION_ALLOC_LIST fal, FUNCTION_TYPES ft
WHERE fal.FUNCTION_TYPE=ft.TYPE and RESOURCE LIKE 'ME%';

SELECT * FROM ITEM_REDIRECT;
SELECT * FROM SORTATION_REASON;

SELECT MER.*,LOC.SUBSYSTEM,LOC.LOCATION 
FROM ITEM_ENCODING_REQUEST MER,LOCATIONS LOC
WHERE MER.LOCATION=LOC.LOCATION_ID;

SELECT * FROM ITEM_ENCODING_REQUEST_TYPES;

--FLIGHT			2	Encoded by Flight Number
--SCANNING			
--DESTINATION		6	Encoded by Airline
--MAKE-UP			3	Encoded by Destination
--BSM				1	Encoded by License Plate Number
--RUNOUT			5	Encoded by Bag Removed
--PROBLEM STATION	4	Encoded by Problem Bag
--LATE BSMS			BSM - IRD 12	Sorted by Unknown License Plate Bag Functional Allocation

DECLARE @DTFROM DATETIME ='2013-10-01';
DECLARE @DTTO DATETIME = '2013-12-09';
EXEC DBO.stp_RPT09_MESUTILIZATION_GWYTEST @DTFROM,@DTTO;

SELECT * FROM ITEM_SCREEN_RESULT_TYPES isrt;
SELECT ICR.TIME_STAMP,ICR.GID,COUNT(ICR.PLC_IDX) AS ICR_TIMES
FROM ITEM_SCREENED ICR
GROUP BY ICR.TIME_STAMP,ICR.GID
HAVING COUNT(ICR.PLC_IDX)>0;

SELECT * FROM ITEM_SCREENED WHERE GID='2113000197'

DROP TABLE TEST1;
CREATE TABLE TEST1(GID VARCHAR(10));
INSERT INTO TEST1 VALUES('0000000011');
INSERT INTO TEST1 VALUES('0000000012');

DROP TABLE TEST2;
CREATE TABLE TEST2(MYEVENT VARCHAR(30), GID VARCHAR(10));
INSERT INTO TEST2 VALUES('EVENT FOR 11 001','0000000011');
INSERT INTO TEST2 VALUES('EVENT FOR 22 012','0000000012');
INSERT INTO TEST2 VALUES('EVENT FOR 33 003','0000000013');
INSERT INTO TEST2 VALUES('EVENT FOR 44 004','0000000014');


SELECT T2.MYEVENT
FROM TEST2 T2
WHERE EXISTS(SELECT * FROM TEST1 T1 WHERE T1.GID=T2.GID);



SELECT T2.MYEVENT
FROM TEST2 T2
WHERE T2.GID IN (SELECT * FROM TEST1 T1);

SELECT count(distinct gid) as num, LICENSE_PLATE1,max(TIME_STAMP)
FROM ITEM_SCANNED
group by LICENSE_PLATE1
having count(distinct gid)>=2;



DECLARE @GID VARCHAR(10)='';
DECLARE @LICENSE_PLATE VARCHAR(10)='0612100122';
DECLARE @DTFROM DATETIME='2013-12-01';
DECLARE @DTTO DATETIME='2013-12-04';
DECLARE @LOGIC VARCHAR(10)='AND';
SELECT * FROM ITEM_SCANNED WHERE TIME_STAMP BETWEEN @DTFROM AND @DTTO;
EXEC stp_RPT27_BAGTRACE_GWYTEST @DTFROM,@DTTO,@GID,@LICENSE_PLATE,@LOGIC;

SELECT 'BAG'+GID
FROM ITEM_SCANNED;

select * from MDS_BAG_COUNT;
select * from MDS_BAG_COUNTERS;
select * from locations;
SELECT * FROM BAGGAGE_MEASURE_ARRAY_MSG;

select * from item_1500p;


SELECT DISTINCT LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_PROCEEDED IPR 
LEFT JOIN LOCATIONS LOC
ON IPR.PROCEED_LOCATION=LOC.LOCATION_ID
	AND LOC.SUBSYSTEM LIKE 'SS1%'
ORDER BY LOC.SUBSYSTEM, LOC.LOCATION;


SELECT DISTINCT LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_SCREENED ICR 
LEFT JOIN LOCATIONS LOC
ON ICR.LOCATION=LOC.LOCATION_ID
	AND LOC.SUBSYSTEM LIKE 'ED%'
ORDER BY LOC.SUBSYSTEM, LOC.LOCATION;

SELECT DISTINCT LOC.SUBSYSTEM, LOC.LOCATION
from locations loc
where LOC.SUBSYSTEM LIKE 'SS%'

select * from MIS_DATE_BASIC;


SELECT BS.AIRLINE,BS.FLIGHT_NUMBER,BS.SURNAME ,BS.SDO,BS.LICENSE_PLATE,isc.GID,ISC.TIME_STAMP,LOC1.SUBSYSTEM,LOC1.LOCATION,LOC2.SUBSYSTEM,LOC2.LOCATION
FROM BAG_SORTING BS,ITEM_SCANNED ISC,LOCATIONS LOC1,ITEM_PROCEEDED IPR,LOCATIONS LOC2
WHERE (BS.LICENSE_PLATE=ISC.LICENSE_PLATE1 OR BS.LICENSE_PLATE=ISC.LICENSE_PLATE2)
	AND ISC.LOCATION=LOC1.LOCATION_ID
	AND LOC1.LOCATION LIKE 'ML%'
	AND IPR.PROCEED_LOCATION=LOC2.LOCATION_ID
	AND LOC2.LOCATION LIKE 'MU%'

SELECT * FROM ITEM_SCANNED ISC WHERE ISC.LICENSE_PLATE1='0176000002' OR ISC.LICENSE_PLATE2='0176000002';

SELECT BS.SURNAME,BS.GIVEN_NAME,BS.OTHERS_NAME FROM BAG_SORTING BS

DECLARE @SDO datetime='2013-12-09';
SET @SDO=CONVERT(VARCHAR,@SDO,103);
SELECT @SDO;

DECLARE @AIRLINE varchar(max)='DL';
DECLARE @FLIGHTNUM varchar(max)='0006';
EXEC stp_RPT01_BAGTAG_GWYTEST @SDO;


SELECT DISTINCT LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_SCREENED ICR, LOCATIONS LOC
WHERE ICR.LOCATION=LOC.LOCATION_ID



SELECT DISTINCT IPR.TIME_STAMP,IPR.GID, LOC.SUBSYSTEM, LOC.LOCATION, PRELOC.SUBSYSTEM, PRELOC.LOCATION, ICRT.DESCRIPTION, ICR.SCREEN_LEVEL
FROM ITEM_SCREENED ICR, ITEM_SCREEN_RESULT_TYPES ICRT, ITEM_PROCEEDED IPR, LOCATIONS LOC, LOCATIONS PRELOC
WHERE IPR.LOCATION=LOC.LOCATION_ID
	AND IPR.PROCEED_LOCATION=PRELOC.LOCATION_ID
	AND (LOC.LOCATION LIKE 'CB%' OR LOC.LOCATION LIKE 'ED%')
	AND ICR.TIME_STAMP>'2013-12-01'
	AND ICR.GID=IPR.GID
	AND ICR.RESULT_TYPE=ICRT.TYPE
ORDER BY IPR.TIME_STAMP DESC
--2013-12-03 14:39:13.603	3211000877	ED4	ED4-17A	ED4	ED4-17B	Machine Alarm / operator clear	3
--2013-12-03 14:39:04.583	3211000876	ED4	ED4-17A	ED4	ED4-17C	Machine Alarm / operator alarm	3

SELECT ICR.* ,ICRT.DESCRIPTION
FROM ITEM_SCREENED ICR, ITEM_SCREEN_RESULT_TYPES ICRT
WHERE ICR.GID='3234000524'
	AND ICR.RESULT_TYPE=ICRT.TYPE

SELECT IPR.*, LOC.SUBSYSTEM,LOC.LOCATION, PRE_LOC.SUBSYSTEM,PRE_LOC.LOCATION
FROM ITEM_PROCEEDED IPR, LOCATIONS LOC, LOCATIONS PRE_LOC
WHERE IPR.LOCATION=LOC.LOCATION_ID AND IPR.PROCEED_LOCATION=PRE_LOC.LOCATION_ID;

SELECT IPR.*,LOC.SUBSYSTEM AS NOWSYS,LOC.LOCATION AS NOWLOC, PRELOC.SUBSYSTEM AS TOSYS,PRELOC.LOCATION AS TOLOC
FROM ITEM_PROCEEDED IPR, LOCATIONS LOC, LOCATIONS PRELOC
WHERE IPR.LOCATION=LOC.LOCATION_ID
	AND IPR.PROCEED_LOCATION=PRELOC.LOCATION_ID
	AND LOC.LOCATION LIKE 'ED%'
	AND TIME_STAMP>'2013-12-19'

SELECT TIME_STAMP,LICENSE_PLATE1,LICENSE_PLATE2 FROM ITEM_SCANNED WHERE GID='3111000513';

SELECT * FROM ITEM_SCANNED WHERE LICENSE_PLATE1='0612000034' OR LICENSE_PLATE2='0612000034'

SELECT ITI.*, LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_TRACKING ITI,LOCATIONS LOC 
WHERE GID='3110000515' AND ITI.LOCATION=LOC.LOCATION_ID

SELECT ICR.*,ICRT.DESCRIPTION
FROM ITEM_SCREENED ICR, ITEM_SCREEN_RESULT_TYPES ICRT 
WHERE ICR.GID='3110000515' AND ICR.RESULT_TYPE=ICRT.TYPE


--GID:3211000083 LP:0612000026 ALARM
--GID:3111000513 LP:0612000031 CLEAR

DECLARE @DTFrom [datetime]='2013-12-19';
DECLARE @DTTo [datetime]='2013-12-21';
EXEC stp_RPT22_ScreeningStatus_GWYTEST @DTFrom,@DTTo;
EXEC stp_RPT22_CRITICALTRACKINGPEC_GWYTEST @DTFrom,@DTTo;

0612000034	EDS01	Entering EDS at ED1-12	2013-12-20 11:35:41.877	Entered
0612000034	EDS01	Exited from EDS at ED1-14	2013-12-20 11:35:59.457	NULL
0612000034	EDS01	At Divert Point: ED1-19A, diverted to ED1-19C	2013-12-20 11:36:15.737	NULL


DECLARE @DTFrom [datetime]='2013-12-19';
DECLARE @DTTo [datetime]='2013-12-21';
exec stp_RPT18_BAGNOTFOUND_GWYTEST @DTFrom,@DTTo;

select * from ITEM_SCANNED isc
where isc.LICENSE_PLATE1='0618000003' and TIME_STAMP='2013-12-19 17:25:43.127'

select * from ITEM_REDIRECT ird where ird.GID='3695678912' and TIME_STAMP>'2013-12-19' and (REASON='11' or REASON='13');

SELECT DISTINCT LOC.SUBSYSTEM, LOC.LOCATION
FROM ITEM_SCANNED ISC, LOCATIONS LOC
WHERE ISC.LOCATION=LOC.LOCATION_ID

DECLARE @DTFrom [datetime]='2013-12-19';
DECLARE @DTTo [datetime]='2013-12-21';
DECLARE @Interval INT=120;
exec stp_RPT26_TIMEINSYSTEM_GWYTEST @DTFrom,@DTTo,@Interval

SELECT * FROM BAG_SORTING;


select ip.*, loc.SUBSYSTEM, loc.LOCATION
from ITEM_1500P ip, LOCATIONS loc
where ip.LOCATION=loc.LOCATION_ID
	AND TIME_STAMP BETWEEN @DTFrom AND @DTTo


DECLARE @DTFrom [datetime]='2013-12-19';
DECLARE @DTTo [datetime]='2013-12-21';

select ip.*
from ITEM_1500P ip
where TIME_STAMP BETWEEN @DTFrom AND @DTTo

EXEC stp_RPT25_CBRASTATISTICS_GWYTEST @DTFrom,@DTTo


DECLARE @DTFrom [datetime]='2013-12-19';
DECLARE @DTTo [datetime]='2013-12-21';
EXEC stp_RPT24_BDDSTATISTICS_OOG_GWYTEST @DTFrom,@DTTo

SELECT COUNT(MER.GID) AS TOTAL, LOC.LOCATION, MER.LOCATION
FROM ITEM_MEASURED MER, LOCATIONS LOC 
where TIME_STAMP BETWEEN @DTFrom AND @DTTo
	AND MER.LOCATION=LOC.LOCATION_ID
GROUP BY LOC.LOCATION,MER.LOCATION;

--1101 1201
SELECT * FROM LOCATIONS WHERE LOCATION IN ('SS1-1','SS2-1');

SELECT * FROM GID_USED GUD 
WHERE GUD.LOCATION IN ('1101','1201') AND TIME_STAMP BETWEEN '2013-12-19' AND '2013-12-21';


SELECT * FROM ITEM_MEASURED_TYPES;
SELECT * FROM ITEM_MEASURED WHERE TIME_STAMP BETWEEN '2013-12-19' AND '2013-12-21';

DECLARE @DTFrom [datetime]='2013-11-19';
DECLARE @DTTo [datetime]='2013-12-21';
DECLARE @INTERVAL INT =60;
DECLARE @SUBSYSTEM VARCHAR(MAX)='ED1,ED2,ED3,ED4,ML01,ML02,ML03,ML04,MU,ME1,ME2,ME3';

--EXEC stp_RPT10_LOADBALANCING_NORMAL @DTFROM,@DTTO,@INTERVAL,@SUBSYSTEM;
EXEC stp_RPT10_LOADBALANCING_EDS @DTFROM,@DTTO;

SELECT * FROM SUBSYSTEMS WHERE SUBSYSTEM LIKE 'MU%';

select * from SubsystemCatalog where DETECT_LOCATION IS NOT NULL OR DETECT_LOCATION<>''

CREATE NONCLUSTERED INDEX #INDEX_MDS_BAG_COUNT_LOCATION ON MDS_BAG_COUNT(TIME_STAMP);
CREATE NONCLUSTERED INDEX #INDEX_MDS_BAG_COUNT_TIMESTAMP ON MDS_BAG_COUNT(TIME_STAMP);
CREATE NONCLUSTERED INDEX #INDEX_MDS_BAG_COUNT_COUNTERID ON MDS_BAG_COUNT(COUNTER_ID);

SELECT COUNT(COUNTER_ID) FROM MDS_BAG_COUNT;

select isc.TIME_STAMP,isc.GID,loc.SUBSYSTEM,loc.LOCATION
from ITEM_SCANNED isc, locations loc 
where isc.LICENSE_PLATE1='0612000031' and isc.LOCATION=loc.LOCATION_ID

SELECT * FROM ITEM_PROCEEDED ipr where ipr.GID='3110000514';
select * from ITEM_SCREENED icr where icr.GID='3110000514';
select * from ITEM_TRACKING iti where iti.GID='3110000514';

---------------------------------------Test for Wenxiong-----------------------------------------------------
Declare @SEARCH_CRITERIA varchar(max)='';
DECLARE @TMP_PATTERN VARCHAR(10), @TMP_DOT VARCHAR(10)
Set @TMP_PATTERN = '%[^0]%'
Set @TMP_DOT = '.';
SET @SEARCH_CRITERIA = @SEARCH_CRITERIA + ' DECLARE @FLIGHT_NUMBER1 VARCHAR(5)=''001''; ';
SET @SEARCH_CRITERIA = @SEARCH_CRITERIA + ' DECLARE @FLIGHT_NUMBER2 VARCHAR(5)=''01''; ';
SET @SEARCH_CRITERIA = @SEARCH_CRITERIA + ' DECLARE @FLIGHT_NUMSUFFIX VARCHAR(5)=''''; ';

SET @SEARCH_CRITERIA= @SEARCH_CRITERIA+
				'IF (SUBSTRING( @FLIGHT_NUMBER1, 
								PATINDEX('+CHAR(39)+@TMP_PATTERN+CHAR(39)+', @FLIGHT_NUMBER1+'+CHAR(39)+@TMP_DOT+CHAR(39)+'), 
								LEN(@FLIGHT_NUMBER1)
							   )
				  = (SUBSTRING(
								@FLIGHT_NUMBER2, 
								PATINDEX('+CHAR(39)+@TMP_PATTERN+CHAR(39)+', @FLIGHT_NUMBER2+'+CHAR(39)+@TMP_DOT+CHAR(39)+'), 
								LEN(@FLIGHT_NUMBER2)
							   ) 
							+ RTRIM(LTRIM(@FLIGHT_NUMSUFFIX)))) 
				PRINT ''OK''; '
PRINT @Search_Criteria;
EXEC(@Search_Criteria);

DECLARE @FLIGHT_NUMBER1 VARCHAR(5)='089';
DECLARE @FLIGHT_NUMBER2 VARCHAR(5)='89';
DECLARE @FLIGHT_NUMSUFFIX VARCHAR(5)='';
select PATINDEX('%[^0]%', @FLIGHT_NUMBER1+ '.');
select PATINDEX('%[^0]%', @FLIGHT_NUMBER2+ '.');

DECLARE @DTFROM DATETIME='10/29/2013 15:00:00';
DECLARE @DTTO DATETIME='10/29/2013 18:00:00';
DECLARE @AIRLINE VARCHAR(3)='GF';
DECLARE @FLIGHT_NUMBER VARCHAR(5)='065';
DECLARE @LP VARCHAR(5)='';
--SELECT * FROM BAG_SORTING
--WHERE  AIRLINE=@AIRLINE AND FLIGHT_NUMBER=@FLIGHT_NUMBER
--	AND TIME_STAMP BETWEEN @DTFROM AND @DTTO;


EXEC DBO.[stp_SAC_BSMView_GWY] @DTFROM,@DTTO,@AIRLINE,@FLIGHT_NUMBER,@LP,'','',''
go

drop table ##IBSM;	
DECLARE @DTFROM DATETIME='10/21/2013 08:00:00 AM';
DECLARE @DTTO DATETIME='10/21/2013 09:00:00 AM';
SELECT DISTINCT BS.[LICENSE_PLATE],
	BS.[DATA_ID],
	BS.[SOURCE],
	BS.[SURNAME],
	BS.[GIVEN_NAME],
	BS.[OTHERS_NAME],
	BS.[SDO],
	BS.[AIRPORT_CODE],
	BS.[TRAVEL_CLASS],
	BS.[TIME_STAMP],
	BS.[ACTION],
	BS.[SECURITY_SCREENING_RESULT_METHOD],
	BS.[AIRLINE] + BS.[FLIGHT_NUMBER] AS [FLIGHT],
	BS.DESTINATION,
	FP.SDO AS SDD,
	FP.STO,
	FP.EDO,
	FP.ETO,
	FP.CUSTOMS_REQUIRED
--INTO ##IBSM
FROM BAG_SORTING BS,
	FLIGHT_PLAN_SORTING FP WITH (NOLOCK)
WHERE LTRIM(RTRIM(BS.AIRLINE)) = LTRIM(RTRIM(FP.AIRLINE))
	AND (SUBSTRING(BS.[FLIGHT_NUMBER], PATINDEX('%[^0]%', BS.[FLIGHT_NUMBER] + '.'), LEN(BS.[FLIGHT_NUMBER])) = (SUBSTRING(FP.[FLIGHT_NUMBER], PATINDEX('%[^0]%', FP.[FLIGHT_NUMBER] + '.'), LEN(FP.[FLIGHT_NUMBER])) + RTRIM(LTRIM(FP.FLIGHT_NUMBER_SUFFIX))))
	AND BS.SDO = FP.SDO
	--AND BS.TIME_STAMP BETWEEN @DTFROM AND @DTTO
	AND BS.AIRLINE = 'GF'
	AND CAST(BS.FLIGHT_NUMBER AS INT) = CAST('65' AS INT);

select * from ##IBSM;

ROLLBACK