select * from REPORT_FAULT where FAULT_DESCRIPTION LIKE '%Status%';
select * from REPORT_FAULT_TYPES;


select * from MDS_ALARMS;
select * from MDS_AUDIT_LOGS;
select TOP 10 * from MDS_BAG_COUNT WHERE TIME_STAMP>'2013-07-01';
select TOP 10 * from MDS_BAG_COUNTERS;
select * from MDS_CONDITION_EVENT_LOGS;
select * from MDS_DATA;
select * from MDS_EVENTS;
select * from MDS_HBS_DATA;
select * from MDS_LOGS;
select * from MDS_MAINTENANCE_STATUS;
select * from MDS_SHAFT_ENCODER_COUNT;

select * from locations loc where loc.LOCATION='SA/SF1';
select * from locations loc where loc.TRACKED<>1;

select * from MDS_ALARMS;
SELECT * FROM BAG_COU

insert into BHSDB.DBO.MDS_ALARMS
SELECT * FROM BHSDB_Phoenix.DBO.MDS_ALARMS;

insert into BHSDB.DBO.MDS_BAG_COUNT
SELECT TIME_STAMP,COUNTER_ID,PREVIOUS_COUNT,CURRENT_COUNT,DIFFERENT,IFIX_NODE 
FROM [BHSDB-Mumbai].DBO.MDS_BAG_COUNT
WHERE TIME_STAMP>'2013-08-01';

insert into BHSDB.DBO.MDS_BAG_COUNTERS
SELECT * FROM [BHSDB-Mumbai].DBO.MDS_BAG_COUNTERS;

insert into BHSDB.DBO.LOCATIONS
SELECT * FROM [BHSDB-Mumbai].DBO.LOCATIONS;

select top 5 * from BHSDB.DBO.LOCATIONS;
select top 5 * from [BHSDB-Mumbai].DBO.LOCATIONS;

DECLARE @DTFrom datetime='2009-11-01';
DECLARE @DTTo datetime='2009-12-31';
DECLARE @Subsystem varchar(max)='AL1,CS1,CL3';
DECLARE @EquipmentID varchar(max)='AL1-01,AL1-07,AL1-08,CS1-01,CS1-02,CS1-04,CL3-01,CL3-11,CL3-12';
DECLARE @FaultType varchar(max)='AA_ENUS,AA_BJAM,AA_ESTP,AA_ENUS,AA_ISOF,AA_CNFT';
--EXEC stp_RPT0501_EquipMalfunction_GWYTEST @DTFrom,@DTTo,@Subsystem,@EquipmentID,@FaultType
--EXEC stp_RPT0502_EquipCorrection_GWYTEST @DTFrom,@DTTo,@Subsystem,@EquipmentID,@FaultType

EXEC stp_RPT08_EquipFaultSummary_GWYTEST @DTFrom,@DTTo,@FaultType;


DECLARE @DTFrom datetime='2013-12-10';
DECLARE @DTTo datetime='2013-12-25';
DECLARE @Subsystem varchar(max)='MF5,MF6,ML01,ML02,ML03,ML04';
EXEC stp_RPT11_RUNOUT @DTFrom,@DTTo,@Subsystem;

select DISTINCT LOC.SUBSYSTEM
from ITEM_SORTATION_EVENT ISC,LOCATIONS LOC
WHERE ISC.LOCATION=LOC.LOCATION_ID AND TIME_STAMP >'2013-12-10'

select * from ITEM_SORTATION_EVENT_TYPES;

select * from ITEM_SORTATION_EVENT ise where ise.GID='086000697'
select * from ITEM_SCANNED ise where ise.GID='086000697'

select * from SUBSYSTEMS where SUBSYSTEM='CS1';
select * from locations where SUBSYSTEM='CS1';



DECLARE @DTFrom datetime='2013-11-01';
DECLARE @DTTo datetime='2013-12-25';
DECLARE @Subsystem varchar(max)='ED1,ED2,ED3,ED4,SS1,SS2';


--SELECT DISTINCT TIME_STAMP, MBCR.SUBSYSTEM,MBCR.LOCATION,LOC.SUBSYSTEM,LOC.LOCATION
--FROM MDS_BAG_COUNT MBC, MDS_BAG_COUNTERS MBCR
--INNER JOIN LOCATIONS LOC ON MBCR.LOCATION=LOC.LOCATION 
--WHERE MBC.COUNTER_ID=MBCR.COUNTER_ID
--	AND TIME_STAMP BETWEEN @DTFrom AND @DTTo
--	AND TRACKED = 1

--select distinct LOC.SUBSYSTEM
--from ITEM_LOST ilt, locations loc
--where ilt.LOCATION=loc.LOCATION_id
--	and time_stamp between @DTFrom AND @DTTo

--select distinct LOC.SUBSYSTEM
--from GID_USED ilt, locations loc
--where ilt.LOCATION=loc.LOCATION_id
--	and time_stamp between @DTFrom AND @DTTo
--	AND BAG_TYPE='02';

EXEC stp_RPT23_TRACKEDPHOTOCELL @DTFrom,@DTTo,@Subsystem;


select * 
from MDS_BAG_COUNT MBC, LOCATIONS LOC


SELECT * FROM REPORT_FAULT
WHERE FAULT_NAME='AA_XBPM' 
	OR FAULT_NAME='AA_RDRV'
	OR FAULT_NAME='AA_NRRV'
	OR FAULT_NAME='AA_ESTP'

SELECT * FROM REPORT_FAULT

SELECT * FROM MDS_ALARMS
WHERE ALM_ALMAREA2='AA_XBPM' 
	OR ALM_ALMAREA2='AA_RDRV'
	OR ALM_ALMAREA2='AA_NRRV'

SELECT ELD.SUBSYSTEM, ELD.EDS_LOCATION
FROM DBO.GET_RPT_EDS_LINE_DEVICE() AS ELD
WHERE ELD.

SELECT ALM_ALMEXTFLD2
FROM MDS_ALARMS
WHERE ALM_UNCERTAIN=1;


SELECT * FROM ITEM_SCREEN_RESULT_TYPES;

SELECT * FROM ITEM_SCREENED
ORDER BY TIME_STAMP DESC;

select *
from locations loc
where loc.SUBSYSTEM='SS1'