go
use BHSDB;
go
BEGIN TRANSACTION;
BEGIN TRY

-- From MDS Alarm
INSERT INTO SUBSYSTEMS VALUES('2TC','2TC');
INSERT INTO SUBSYSTEMS VALUES('3TC','3TC');
INSERT INTO SUBSYSTEMS VALUES('5TC','5TC');
INSERT INTO SUBSYSTEMS VALUES('AL1','AL1');
INSERT INTO SUBSYSTEMS VALUES('AL2','AL2');
INSERT INTO SUBSYSTEMS VALUES('AL3','AL3');
INSERT INTO SUBSYSTEMS VALUES('AL4','AL4');
INSERT INTO SUBSYSTEMS VALUES('BHS','BHS');
INSERT INTO SUBSYSTEMS VALUES('BRL1','BRL1');
INSERT INTO SUBSYSTEMS VALUES('CD1','CD1');
INSERT INTO SUBSYSTEMS VALUES('CD2','CD2');
INSERT INTO SUBSYSTEMS VALUES('CL1','CL1');
INSERT INTO SUBSYSTEMS VALUES('CL2','CL2');
INSERT INTO SUBSYSTEMS VALUES('CL3','CL3');
INSERT INTO SUBSYSTEMS VALUES('CL4','CL4');
INSERT INTO SUBSYSTEMS VALUES('CL5','CL5');
INSERT INTO SUBSYSTEMS VALUES('CL6','CL6');
INSERT INTO SUBSYSTEMS VALUES('CS2','CS2');
INSERT INTO SUBSYSTEMS VALUES('CS3','CS3');
INSERT INTO SUBSYSTEMS VALUES('CS4','CS4');
INSERT INTO SUBSYSTEMS VALUES('CS5','CS5');
INSERT INTO SUBSYSTEMS VALUES('CS6','CS6');
INSERT INTO SUBSYSTEMS VALUES('MES','MES');
INSERT INTO SUBSYSTEMS VALUES('MF1','MF1');
INSERT INTO SUBSYSTEMS VALUES('MF2','MF2');
INSERT INTO SUBSYSTEMS VALUES('MF3','MF3');
INSERT INTO SUBSYSTEMS VALUES('MF4','MF4');
INSERT INTO SUBSYSTEMS VALUES('MU1','MU1');
INSERT INTO SUBSYSTEMS VALUES('MU2','MU2');
INSERT INTO SUBSYSTEMS VALUES('MU3','MU3');
INSERT INTO SUBSYSTEMS VALUES('MU4','MU4');
INSERT INTO SUBSYSTEMS VALUES('MU5','MU5');
INSERT INTO SUBSYSTEMS VALUES('MU6','MU6');
INSERT INTO SUBSYSTEMS VALUES('NR1','NR1');
INSERT INTO SUBSYSTEMS VALUES('OG1','OG1');
INSERT INTO SUBSYSTEMS VALUES('OG2','OG2');
INSERT INTO SUBSYSTEMS VALUES('SF1','SF1');
INSERT INTO SUBSYSTEMS VALUES('SF2','SF2');
INSERT INTO SUBSYSTEMS VALUES('SVR','SVR');
INSERT INTO SUBSYSTEMS VALUES('TC2','TC2');
INSERT INTO SUBSYSTEMS VALUES('TC3','TC3');
INSERT INTO SUBSYSTEMS VALUES('TC5','TC5');
INSERT INTO SUBSYSTEMS VALUES('XO2','XO2');


--From MDS Bag Count
--None

END TRY
BEGIN CATCH
	IF @@TRANCOUNT>0
		ROLLBACK TRANSACTION;
	THROW
END CATCH;

IF @@TRANCOUNT>0
	COMMIT TRANSACTION;